### PR TITLE
Remove `unsafe`

### PR DESCRIPTION
**Pull request by SimonSapin**
Rewrite some code to avoid using `unsafe` at all.

### CODE REVIEW

**Comment by dylanede** [comment]
Ah, thanks. I'd forgotten about `truncate`. Regarding the `Vec` initialisation, would it be more efficient in terms of LLVM optimisation if the `type_` field was set to zero, making the whole dummy struct zero?

**Comment by dylanede** [comment]
I'll merge this when I have a moment to do this, tweak some other things and start a changelog.

**Comment by SimonSapin** [comment]
Re zero `type_`, I don’t know. Feel free to change it, or let me know if you want me to.

**Comment by alexheretic** [comment]
This pr was part-merged over at https://gitlab.redox-os.org/redox-os/stb_truetype-rs/merge_requests/1. See discussion there plus https://gitlab.redox-os.org/redox-os/stb_truetype-rs/issues/15

This pr can be closed.

**Comment by SimonSapin** [comment]
It’s been a while so I don’t remember the details of what I had in mind when opening this PR, but the remaining unsafe code still looks worrying, as it is creating uninitialized memory. I think it merits at least a code comment explaining why it is believed that this code is sound, that is that all of the memory (each field of each `Vertex` value) is initialized before it is used, document what someone who works in this code in the future needs to be extra careful about.

**Comment by alexheretic** [comment]
My plan is to remove the final unsafe usage and keep the lib safe onwards. If at all possible I want to do so without damaging performance, see https://gitlab.redox-os.org/redox-os/stb_truetype-rs/issues/15.

**Comment by alexheretic** [comment]
`0.2.4` is all safe rust. This can be closed.

**Pull request closed without merging**
